DROP TABLE IF EXISTS raw_data;
DROP TABLE IF EXISTS truck_calls;
DROP TABLE IF EXISTS forecasts;
DROP TABLE IF EXISTS thresholds;
DROP TABLE IF EXISTS drivers;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS routes;
DROP TABLE IF EXISTS warehouses;