// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: logistics/logistics.proto

package logistics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetrainStatus int32

const (
	RetrainStatus_RETRAIN_STATUS_UNSPECIFIED RetrainStatus = 0
	RetrainStatus_RETRAIN_STATUS_IDLE        RetrainStatus = 1
	RetrainStatus_RETRAIN_STATUS_RUNNING     RetrainStatus = 2
)

// Enum value maps for RetrainStatus.
var (
	RetrainStatus_name = map[int32]string{
		0: "RETRAIN_STATUS_UNSPECIFIED",
		1: "RETRAIN_STATUS_IDLE",
		2: "RETRAIN_STATUS_RUNNING",
	}
	RetrainStatus_value = map[string]int32{
		"RETRAIN_STATUS_UNSPECIFIED": 0,
		"RETRAIN_STATUS_IDLE":        1,
		"RETRAIN_STATUS_RUNNING":     2,
	}
)

func (x RetrainStatus) Enum() *RetrainStatus {
	p := new(RetrainStatus)
	*p = x
	return p
}

func (x RetrainStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetrainStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_logistics_logistics_proto_enumTypes[0].Descriptor()
}

func (RetrainStatus) Type() protoreflect.EnumType {
	return &file_logistics_logistics_proto_enumTypes[0]
}

func (x RetrainStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetrainStatus.Descriptor instead.
func (RetrainStatus) EnumDescriptor() ([]byte, []int) {
	return file_logistics_logistics_proto_rawDescGZIP(), []int{0}
}

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`                    // идентификатор маршрута из датасета
	OfficeFromId  string                 `protobuf:"bytes,2,opt,name=office_from_id,json=officeFromId,proto3" json:"office_from_id,omitempty"`   // идентификатор склада из датасета
	TimestampUnix int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"` // момент времени (Unix секунды)
	HorizonHours  int32                  `protobuf:"varint,4,opt,name=horizon_hours,json=horizonHours,proto3" json:"horizon_hours,omitempty"`    // горизонт прогноза в часах (обычно 2)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_logistics_logistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logistics_logistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_logistics_logistics_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *PredictRequest) GetOfficeFromId() string {
	if x != nil {
		return x.OfficeFromId
	}
	return ""
}

func (x *PredictRequest) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *PredictRequest) GetHorizonHours() int32 {
	if x != nil {
		return x.HorizonHours
	}
	return 0
}

type PredictReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PredictedCount float64                `protobuf:"fixed64,1,opt,name=predicted_count,json=predictedCount,proto3" json:"predicted_count,omitempty"` // предсказанное кол-во ёмкостей (target_2h)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PredictReply) Reset() {
	*x = PredictReply{}
	mi := &file_logistics_logistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictReply) ProtoMessage() {}

func (x *PredictReply) ProtoReflect() protoreflect.Message {
	mi := &file_logistics_logistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictReply.ProtoReflect.Descriptor instead.
func (*PredictReply) Descriptor() ([]byte, []int) {
	return file_logistics_logistics_proto_rawDescGZIP(), []int{1}
}

func (x *PredictReply) GetPredictedCount() float64 {
	if x != nil {
		return x.PredictedCount
	}
	return 0
}

type RetrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromDateUnix  int64                  `protobuf:"varint,1,opt,name=from_date_unix,json=fromDateUnix,proto3" json:"from_date_unix,omitempty"` // начало диапазона данных (0 = с начала)
	ToDateUnix    int64                  `protobuf:"varint,2,opt,name=to_date_unix,json=toDateUnix,proto3" json:"to_date_unix,omitempty"`       // конец диапазона данных (0 = до конца)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrainRequest) Reset() {
	*x = RetrainRequest{}
	mi := &file_logistics_logistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrainRequest) ProtoMessage() {}

func (x *RetrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logistics_logistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrainRequest.ProtoReflect.Descriptor instead.
func (*RetrainRequest) Descriptor() ([]byte, []int) {
	return file_logistics_logistics_proto_rawDescGZIP(), []int{2}
}

func (x *RetrainRequest) GetFromDateUnix() int64 {
	if x != nil {
		return x.FromDateUnix
	}
	return 0
}

func (x *RetrainRequest) GetToDateUnix() int64 {
	if x != nil {
		return x.ToDateUnix
	}
	return 0
}

type RetrainReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "started" | "already_running" | "error"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrainReply) Reset() {
	*x = RetrainReply{}
	mi := &file_logistics_logistics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrainReply) ProtoMessage() {}

func (x *RetrainReply) ProtoReflect() protoreflect.Message {
	mi := &file_logistics_logistics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrainReply.ProtoReflect.Descriptor instead.
func (*RetrainReply) Descriptor() ([]byte, []int) {
	return file_logistics_logistics_proto_rawDescGZIP(), []int{3}
}

func (x *RetrainReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RetrainReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RetrainStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        RetrainStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=logistics.RetrainStatus" json:"status,omitempty"`
	Progress      float64                `protobuf:"fixed64,2,opt,name=progress,proto3" json:"progress,omitempty"` // 0.0 – 1.0
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrainStatusReply) Reset() {
	*x = RetrainStatusReply{}
	mi := &file_logistics_logistics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrainStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrainStatusReply) ProtoMessage() {}

func (x *RetrainStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_logistics_logistics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrainStatusReply.ProtoReflect.Descriptor instead.
func (*RetrainStatusReply) Descriptor() ([]byte, []int) {
	return file_logistics_logistics_proto_rawDescGZIP(), []int{4}
}

func (x *RetrainStatusReply) GetStatus() RetrainStatus {
	if x != nil {
		return x.Status
	}
	return RetrainStatus_RETRAIN_STATUS_UNSPECIFIED
}

func (x *RetrainStatusReply) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *RetrainStatusReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_logistics_logistics_proto protoreflect.FileDescriptor

const file_logistics_logistics_proto_rawDesc = "" +
	"\n" +
	"\x19logistics/logistics.proto\x12\tlogistics\x1a\x1bgoogle/protobuf/empty.proto\"\x9d\x01\n" +
	"\x0ePredictRequest\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12$\n" +
	"\x0eoffice_from_id\x18\x02 \x01(\tR\fofficeFromId\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix\x12#\n" +
	"\rhorizon_hours\x18\x04 \x01(\x05R\fhorizonHours\"7\n" +
	"\fPredictReply\x12'\n" +
	"\x0fpredicted_count\x18\x01 \x01(\x01R\x0epredictedCount\"X\n" +
	"\x0eRetrainRequest\x12$\n" +
	"\x0efrom_date_unix\x18\x01 \x01(\x03R\ffromDateUnix\x12 \n" +
	"\fto_date_unix\x18\x02 \x01(\x03R\n" +
	"toDateUnix\"@\n" +
	"\fRetrainReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"|\n" +
	"\x12RetrainStatusReply\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.logistics.RetrainStatusR\x06status\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x01R\bprogress\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*d\n" +
	"\rRetrainStatus\x12\x1e\n" +
	"\x1aRETRAIN_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RETRAIN_STATUS_IDLE\x10\x01\x12\x1a\n" +
	"\x16RETRAIN_STATUS_RUNNING\x10\x022\x89\x02\n" +
	"\tMLService\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\aPredict\x12\x19.logistics.PredictRequest\x1a\x17.logistics.PredictReply\x12=\n" +
	"\aRetrain\x12\x19.logistics.RetrainRequest\x1a\x17.logistics.RetrainReply\x12F\n" +
	"\rRetrainStatus\x12\x16.google.protobuf.Empty\x1a\x1d.logistics.RetrainStatusReplyB#Z!logistics-service/proto/logisticsb\x06proto3"

var (
	file_logistics_logistics_proto_rawDescOnce sync.Once
	file_logistics_logistics_proto_rawDescData []byte
)

func file_logistics_logistics_proto_rawDescGZIP() []byte {
	file_logistics_logistics_proto_rawDescOnce.Do(func() {
		file_logistics_logistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logistics_logistics_proto_rawDesc), len(file_logistics_logistics_proto_rawDesc)))
	})
	return file_logistics_logistics_proto_rawDescData
}

var file_logistics_logistics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_logistics_logistics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_logistics_logistics_proto_goTypes = []any{
	(RetrainStatus)(0),         // 0: logistics.RetrainStatus
	(*PredictRequest)(nil),     // 1: logistics.PredictRequest
	(*PredictReply)(nil),       // 2: logistics.PredictReply
	(*RetrainRequest)(nil),     // 3: logistics.RetrainRequest
	(*RetrainReply)(nil),       // 4: logistics.RetrainReply
	(*RetrainStatusReply)(nil), // 5: logistics.RetrainStatusReply
	(*emptypb.Empty)(nil),      // 6: google.protobuf.Empty
}
var file_logistics_logistics_proto_depIdxs = []int32{
	0, // 0: logistics.RetrainStatusReply.status:type_name -> logistics.RetrainStatus
	6, // 1: logistics.MLService.Ping:input_type -> google.protobuf.Empty
	1, // 2: logistics.MLService.Predict:input_type -> logistics.PredictRequest
	3, // 3: logistics.MLService.Retrain:input_type -> logistics.RetrainRequest
	6, // 4: logistics.MLService.RetrainStatus:input_type -> google.protobuf.Empty
	6, // 5: logistics.MLService.Ping:output_type -> google.protobuf.Empty
	2, // 6: logistics.MLService.Predict:output_type -> logistics.PredictReply
	4, // 7: logistics.MLService.Retrain:output_type -> logistics.RetrainReply
	5, // 8: logistics.MLService.RetrainStatus:output_type -> logistics.RetrainStatusReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_logistics_logistics_proto_init() }
func file_logistics_logistics_proto_init() {
	if File_logistics_logistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logistics_logistics_proto_rawDesc), len(file_logistics_logistics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logistics_logistics_proto_goTypes,
		DependencyIndexes: file_logistics_logistics_proto_depIdxs,
		EnumInfos:         file_logistics_logistics_proto_enumTypes,
		MessageInfos:      file_logistics_logistics_proto_msgTypes,
	}.Build()
	File_logistics_logistics_proto = out.File
	file_logistics_logistics_proto_goTypes = nil
	file_logistics_logistics_proto_depIdxs = nil
}
